services:
  mon-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Data Source=/app/data/data.db3
      - JWT__PrivateKey=${JWT__PrivateKey}
      - JWT__PublicKey=${JWT__PublicKey}
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - mon-api

  mobile-app:
    build:
      context: ./mobile-app
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - mon-api
