sonar.organization=matth-s
sonar.projectKey=matth-s_RessourceRelationnelle_MOBILE
sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

sonar.language=js
sonar.sources=src
sonar.tests=src/__test__
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Fichiers complètement exclus de l'analyse Sonar
sonar.exclusions=node_modules/**,src/__test__/**

# ALIGNEMENT : Fichiers exclus uniquement du calcul du score de COUVERTURE
sonar.coverage.exclusions=src/assets/**,**/*.config.ts,**/*.d.ts,src/__test__/scenarios/**,src/types/fetch-key-type.ts,src/types/dashboard-stat-enum.ts,src/lib/**,src/App.tsx,src/main.tsx,**/store/**,**/hooks/**,**/schemas/**,**/slice/**,**/constants/**,**/components/**,src/pages/**,src/app/**,src/layouts/**

sonar.qualityGate.wait=false