sonar.organization=Matth-s
sonar.projectKey=matth-s_RessourceRelationnelle_BACK8OFFICE
sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

sonar.language=js
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/*,test/*
sonar.qualityGate.wait=false