sonar.organization=Matth-s
sonar.projectKey=matth-s_RessourceRelationnelle_MOBILE
sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

sonar.language=js
sonar.sources=src
sonar.tests=__test__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/*,__test__/*
sonar.qualityGate.wait=false