export const FETCH_KEYS = {
  CATEGORY: "CATEGORY",
  USERS: "USERS",
  COMMENTS: "COMMENTS",
  RESOURCES: "RESOURCES",
  STATISTICS: "STATISTICS",
  RELATION: "RELATION",
  RESOURCE_TYPE: "RESOURCE_TYPE",
} as const;
