name: 01-3 - Integration - SNYK

on: workflow_call

jobs:
  SecurityBack:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore RessourceRelationnelle.API.sln

      - name: Run Snyk Test
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=medium --file=./backend/RessourceRelationnelle.API.sln --org=${{ secrets.SNYK_ORG_ID }}

      - name: Run Snyk Monitor
        if: always()
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --severity-threshold=medium --file=./backend/RessourceRelationnelle.API.sln --org=${{ secrets.SNYK_ORG_ID }}

  SecurityFront:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin-frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: install dep
        run: npm i

      - name: Run Snyk Test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=critical --file=./admin-frontend/package.json --org=${{secrets.SNYK_ORG_ID}}

      - name: Run Snyk Monitor
        if: always()
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --severity-threshold=critical --file=./admin-frontend/package.json --org=${{secrets.SNYK_ORG_ID}}

  SecurityMobile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile-app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: install dep
        run: npm i

      - name: Run Snyk Test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=critical --file=./mobile-app/package.json --org=${{secrets.SNYK_ORG_ID}}

      - name: Run Snyk Monitor
        if: always()
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --severity-threshold=critical --file=./mobile-app/package.json --org=${{secrets.SNYK_ORG_ID}}
