name: 🔄 Redémarrage Manuel API

on:
  workflow_dispatch:

jobs:
  reboot:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH et Redémarrage
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            
            cd /var/www/ressource-api/backend
            
            docker compose restart mon-api
